import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import SearchBar from '../components/SearchBar'

export default function Home() {
  return (
    <div className='w-full'>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Header />
      <SearchBar />
    </div>
  )
}
